version: 2
jobs:
    build:
      docker:
        - image: circleci/node:latest
      steps:
          - checkout
          - run:
              name: Versions
              command: |
                node --version
                npm --version
          - run:
              name: Dependencies
              command: npm install
          - run:
              name: Compile
              command: ./node_modules/typescript/bin/tsc
          - run:
              name: Tests
              command: npm test
          - setup_remote_docker:
              docker_layer_caching: true
          - run:
              name: Publish
              command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t brandonfitzgibbon/repo:$TAG .
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push brandonfitzgibbon/repo:$TAG
workflows:
    version: 2
    workflow:
        jobs:
        - build:
            context: DockerHub
