version: 2
jobs:
    build:
      docker:
        - image: circleci/node:latest
      steps:
          - checkout
          - run:
              name: Versions
              command: |
                node --version
                npm --version
          - run:
              name: Dependencies
              command: npm install
          - run:
              name: Compile
              command: ./node_modules/typescript/bin/tsc
          - run:
              name: Tests
              command: npm test
