version: 2
executors:
    primary:
        docker:
            - image: circleci/node:latest
        working_directory: /tmp

jobs:
    build:
      executor: primary
      steps:
          - checkout
          - run:
              name: Versions
              command: |
                node --version
                npm --version
          - run:
              name: Dependencies
              command: npm install
          - run:
              name: Compile
              command: ./node_modules/typescript/bin/tsc
          - run:
              name: Tests
              command: npm test
          - persist_to_workspace:
              root: dist
              paths:
                - .
    publish:
        executor: primary
        steps:
          - attach_workspace:
              at: /tmp/dist
          - setup_remote_docker:
              docker_layer_caching: true
          - run:
              name: Publish
              command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                sudo apt-get install python-pip python-dev
                sudo pip install awscli
                aws configure set aws_access_key_id $AWS_ACCESS
                configure set aws_secret_access_key $AWS_SECRET
                $(aws ecr get-login --no-include-email --region ca-central-1)
                docker build -t homework .
                docker tag homework:$TAG 160447282053.dkr.ecr.ca-central-1.amazonaws.com/homework:$TAG
                docker push 160447282053.dkr.ecr.ca-central-1.amazonaws.com/homework:$TAG
workflows:
    version: 2
    workflow:
        jobs:
        - build
        - publish:
            context: AWS Deploy
            requires:
              - build
