openapi: 3.0.0
info:
  title: forum
  description: forum api spec for homework project
  version: 0.0.1
servers:
  - url: http://localhost:8001/
    description: local server
  - url: https://api.brandonfitzgibbon.com
    description: production server
paths:
  /:
    get:
      summary: health check for endpoint monitoring
      tags:
        - health
      operationId: health
      responses:
        '200':
          description: healthy endpoint
  /entries:
    get:
      summary: gets all forum post entries
      operationId: getEntries
      tags:
        - entries
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: name of entry author
      responses:
        '200':
          description: a JSON array of entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/entry'
        '503':
          description: something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
    post:
      summary: creates a new forum post entries
      operationId: postEntries
      tags:
        - entries
      requestBody:
        description: a JSON object representing an entry
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/entry'
      responses:
        '200':
          description: a JSON object containing the entry text
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/entry'
        '503':
          description: something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
components:
  schemas:
    dataItem:
      type: object
      required:
        - _id
      properties:
        _id:
          type: string
          readOnly: true
    entry:
      allOf:
        - $ref: '#/components/schemas/dataItem'
        - type: object
          required: 
            - content
            - name
            - dateTime
          properties:
            content:
              type: string
            name:
              type: string
            dateTime:
              type: string
              format: date-time
              readOnly: true
    errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/error'
    error:
      type: object
      properties:
        errorCode:
          type: string
        location:
          type: string
        message:
          type: string
        path:
          type: string